// Bahasa Melayu translations — batch 1 (partial: s-1, s-2; more sections appended as translated).
// Format: one object per section; kind/annotation merged from English source by scripts/merge-bm.mjs.
export default [
  {
    id: 's-1',
    heading: 'Tajuk ringkas',
    content: [
      {
        kind: 'item',
        text: '(1) Akta ini bolehlah dirujuk sebagai Akta Kastam 1967. (2) (Disingkirkan).',
      },
    ],
  },
  {
    id: 's-2',
    heading: 'Takrif',
    content: [
      {
        kind: 'item',
        text: '(1) Dalam Akta ini, melainkan jika konteksnya memerlukan lain--',
      },
      {
        kind: 'quote',
        term: 'ejen',
        text: ", berkenaan dengan kapal termasuklah chinchew dan comprador; \"orang yang diberi akreditasi\" ialah mana-mana orang yang telah diluluskan oleh Ketua Pengarah di bawah seksyen 88B;'",
        items: [],
      },
      {
        kind: 'quote',
        term: 'lapangan terbang kastam',
        text: 'bermaksud mana-mana tempat yang telah ditetapkan sebagai lapangan terbang kastam;',
        items: [],
      },
      {
        kind: 'quote',
        term: 'penyiapan kastam',
        text: 'bermaksud penyempurnaan prosedur kastam yang berkenaan untuk membolehkan barang--',
        items: [
          '(a) dilepaskan untuk penggunaan tempatan;',
          '(b) dieksportkan; atau',
          '(c) diletakkan di bawah suatu prosedur kastam yang lain;',
        ],
      },
      {
        kind: 'quote',
        term: 'kawalan kastam',
        text: "bermaksud langkah-langkah yang dijalankan oleh pegawai-pegawai kastam sebelum pelepasan barang bagi memastikan pematuhan dengan Akta ini;'",
        items: [],
      },
      {
        kind: 'quote',
        term: 'duti kastam',
        text: 'bermaksud mana-mana duti import, duti eksport, cukai tambahan, caj tambahan atau ses yang dikenakan oleh atau di bawah Akta ini, mana-mana duti tindakan balas atau duti anti-lumping yang dikenakan oleh atau di bawah Akta Duti Tindakan Balas dan Anti-Dumping 1993 [Akta 504], mana-mana duti langkah perlindungan yang dikenakan oleh atau di bawah Akta Langkah-Langkah Perlindungan 2006 [Akta 657] dan termasuklah mana-mana royalti yang perlu dibayar sebagai ganti bagi suatu duti eksport di bawah mana-mana undang-undang bertulis, atau suatu kontrak, pajakan atau perjanjian yang Kerajaan Persekutuan atau Kerajaan mana-mana Negeri adalah satu pihak kepadanya atau yang Kerajaan sedemikian telah bersetuju kepadanya;',
        items: [],
      },
      {
        kind: 'quote',
        term: 'pejabat kastam',
        text: 'bermaksud unit pentadbiran kastam yang bertanggungjawab bagi penyempurnaan fungsi-fungsi dan tugas-tugas berkenaan kastam, dan premis yang digunakan, atau tempat-tempat lain yang diluluskan, dilesenkan atau ditetapkan, bagi tujuan itu di bawah Akta ini;',
        items: [],
      },
      {
        kind: 'quote',
        term: 'pelabuhan kastam',
        text: 'bermaksud mana-mana pelabuhan yang ditetapkan sebagai pelabuhan kastam;',
        items: [],
      },
      {
        kind: 'quote',
        term: 'putusan kastam',
        text: 'bermaksud putusan kastam yang dibuat oleh Ketua Pengarah di bawah seksyen 10B;',
        items: [],
      },
      {
        kind: 'quote',
        term: 'gudang kastam',
        text: 'bermaksud suatu gudang atau tempat lain yang ditubuhkan oleh Menteri di bawah subseksyen 63(1) bagi penyimpanan barang yang dikenakan duti;',
        items: [],
      },
      {
        kind: 'quote',
        term: 'perisytiharan asal',
        text: 'bermaksud suatu kenyataan yang sewajarnya berkenaan dengan asal barang berhubung dengan import atau eksportnya oleh pengimport, pengeluar atau pengeksport pada invois komersil atau mana-mana dokumen berkenaan dengan barang;',
        items: [],
      },
      {
        kind: 'quote',
        term: 'dinyahaktif',
        text: 'bermaksud dijadikan dengan berkesan tidak sesuai untuk penggunaan manusia kepada kepuasan Ketua Pengarah;',
        items: [],
      },
      {
        kind: 'quote',
        term: 'Ketua Pengarah',
        text: 'bermaksud Ketua Pengarah Kastam dan Eksais yang dilantik di bawah subseksyen 3(1);',
        items: [],
      },
      {
        kind: 'quote',
        term: 'dokumen',
        text: 'mempunyai makna yang diberikan kepadanya dalam seksyen 3 Akta Keterangan 1950;',
        items: [],
      },
      {
        kind: 'quote',
        term: 'barang yang dikenakan duti',
        text: 'bermaksud semua barang yang tertakluk kepada pembayaran duti kastam dan yang duti sedemikian belum lagi dibayar ke atasnya;',
        items: [],
      },
      {
        kind: 'quote',
        term: 'kedai bebas duti',
        text: 'bermaksud mana-mana tempat yang dilesenkan bagi penggudangan dan jualan barang yang dikenakan duti secara bebas duti di bawah seksyen 65D;',
        items: [],
      },
      {
        kind: 'quote',
        term: 'pertukaran data elektronik',
        text: 'bermaksud pemindahan, dari komputer ke komputer, bagi urus niaga komersial dan pentadbiran menggunakan suatu piawaian mesej yang dipersetujui untuk menyusun data berkenaan dengan suatu urus niaga;',
        items: [],
      },
      {
        kind: 'quote',
        term: 'eksport',
        text: 'bermaksud membawa atau menyebabkan dibawa keluar dari Malaysia, melalui darat, laut, udara, atau dengan cara lain atau meletakkan mana-mana barang di dalam suatu pengangkutan bagi tujuan barang sedemikian dibawa keluar dari Malaysia melalui darat, laut, udara, atau dengan cara lain;',
        items: [],
      },
      {
        kind: 'quote',
        term: 'eksport melalui udara',
        text: 'termasuklah pengeksportan dengan apa-apa cara atau melalui apa-apa jalan udara;',
        items: [],
      },
      {
        kind: 'quote',
        term: 'eksport melalui darat',
        text: 'termasuklah pengeksportan dengan apa-apa cara atau melalui apa-apa jalan darat, dan termasuklah, khasnya, pengeksportan melalui darat dengan jalan paip;',
        items: [],
      },
      {
        kind: 'quote',
        term: 'eksport melalui laut',
        text: 'termasuklah pengeksportan dengan apa-apa cara atau melalui apa-apa jalan laut, dan termasuklah, khasnya, pengeksportan melalui laut dengan jalan paip;',
        items: [],
      },
      {
        kind: 'quote',
        term: 'pengeksport',
        text: "termasuklah mana-mana orang yang barangnya (termasuklah barang yang dipindahkan dari suatu kapal terbang atau kapal yang mengimport) dieksportkan dari Malaysia atau dibekalkan untuk kegunaan sebagai simpanan kapal terbang atau kapal, dan juga pemiliknya, atau mana-mana orang yang bertindak bagi pihaknya, dan mana-mana orang yang bagi tujuan kastam menandatangani mana-mana dokumen berkenaan dengan barang yang dieksportkan atau ditujukan untuk dieksportkan atau dibekalkan atau ditujukan untuk dibekalkan sebagai simpanan kapal terbang atau kapal sebagaimana tersebut;",
        items: [],
      },
      {
        kind: 'quote',
        term: 'Pihak Berkuasa Kewangan',
        text: 'berkenaan dengan Sabah dan Sarawak bermaksud mana-mana orang yang dilantik oleh Menteri, melalui pemberitahuan dalam Warta yang berkenaan, untuk menjalankan di bawah arahan Menteri mana-mana fungsi yang Menteri diberi kuasa atau dikehendaki oleh Akta ini menjalankannya di Sabah atau Sarawak;',
        items: [],
      },
      {
        kind: 'quote',
        term: 'barang',
        text: 'termasuklah binatang, burung, ikan, tumbuhan, wang dan instrumen boleh runding pembawa dan apa-apa jenis harta alih yang lain;',
        items: [],
      },
      {
        kind: 'quote',
        term: 'berlegar',
        text: 'bagi suatu kapal di perairan wilayah bermaksud berkhemah tanpa tujuan undang-undang yang jelas, sama ada kapal sedemikian sedang bergerak atau tidak;',
        items: [],
      },
      {
        kind: 'quote',
        term: 'import',
        text: 'bermaksud membawa atau menyebabkan dibawa masuk ke Malaysia, melalui darat, laut atau udara atau dengan cara lain;',
        items: [],
      },
      {
        kind: 'quote',
        term: 'import melalui udara',
        text: 'termasuklah pengimportan dengan apa-apa cara atau melalui apa-apa jalan udara;',
        items: [],
      },
      {
        kind: 'quote',
        term: 'import melalui darat',
        text: 'termasuklah pengimportan dengan apa-apa cara atau melalui apa-apa jalan darat, dan termasuklah, khasnya, pengimportan melalui darat dengan jalan paip;',
        items: [],
      },
      {
        kind: 'quote',
        term: 'import melalui laut',
        text: 'termasuklah pengimportan dengan apa-apa cara atau melalui apa-apa jalan laut, dan termasuklah, khasnya, pengimportan melalui laut dengan jalan paip;',
        items: [],
      },
      {
        kind: 'quote',
        term: 'pengimport',
        text: 'termasuklah--',
        items: [
          '(a) mana-mana pemilik atau orang lain yang untuk masa memiliki atau berkepentingan sebenar dalam mana-mana barang pada dan dari masa importnya sehingga barang sedemikian dikeluarkan dengan sah daripada kawalan kastam; dan',
          '(b) berkenaan dengan barang yang diimport melalui jalan paip, pemilik paip itu;',
        ],
      },
      {
        kind: 'quote',
        term: 'depot penyiapan darat',
        text: 'bermaksud suatu kemudahan darat kegunaan bersama yang dilengkapi dengan pemasangan tetap dan menawarkan perkhidmatan bagi pengendalian dan penyimpanan sementara apa-apa jenis barang yang dibawa melalui darat dan diletakkan di bawah kawalan kastam;',
        items: [],
      },
      {
        kind: 'quote',
        term: 'air beralkohol',
        text: 'termasuklah mana-mana alkohol, atau mana-mana cecair yang mengandungi lebih daripada 1.14 peratus isipadu ke atas isipadu alkohol, yang sesuai atau bertujuan untuk dijadikan, atau yang boleh dengan apa-apa cara ditukarkan, untuk kegunaan sebagai minuman;',
        items: [],
      },
      {
        kind: 'quote',
        term: 'pihak berkuasa penerbit',
        text: 'bermaksud suatu badan atau agensi kerajaan yang dilantik di bawah seksyen 99c;',
        items: [],
      },
      {
        kind: 'quote',
        term: 'dalam transit',
        text: '(dihapuskan).',
        items: [],
      },
      {
        kind: 'quote',
        term: 'Kawasan Pembangunan Bersama',
        text: 'mempunyai makna yang diberikan kepadanya dalam seksyen 2 Akta Pihak Berkuasa Bersama Malaysia-Thailand 1990;',
        items: [],
      },
      {
        kind: 'quote',
        term: 'tempat pendaratan yang sah',
        text: 'bermaksud mana-mana tempat yang telah ditetapkan sebagai tempat yang sah untuk pendaratan dan pemunggahan barang;',
        items: [],
      },
      {
        kind: 'quote',
        term: 'pengangkut berlesen',
        text: 'bermaksud orang yang diluluskan oleh Ketua Pengarah untuk mengendalikan kenderaan melalui darat bagi pengangkutan mana-mana barang dalam transit atau mana-mana barang yang dikenakan duti di bawah Akta ini atau di bawah Akta Eksais 1976 [Akta 176];',
        items: [],
      },
      {
        kind: 'quote',
        term: 'gudang berlesen',
        text: 'bermaksud suatu gudang atau tempat lain yang dilesenkan bagi penggudangan barang yang dikenakan duti di bawah seksyen 65;',
        items: [],
      },
      {
        kind: 'quote',
        term: 'kraf tempatan',
        text: 'bermaksud mana-mana jong, tongkang, perahu, kumpit atau jenis kapal serupa yang lain, dan mana-mana kapal stim atau motor di bawah tujuh puluh lima tan bersih berdaftar;',
        items: [],
      },
      {
        kind: 'quote',
        term: 'pengilangan',
        text: 'bermaksud--',
        items: [
          '(a) bagi air beralkohol, penyulingan, pembuatan bir, penapaian, pembotolan air beralkohol, dan termasuklah penambahan mana-mana bahan (selain air) kepada mana-mana air beralkohol dan pencampuran, penggabungan dan pengubahan air-air beralkohol dengan niat supaya gabungan yang terbentuk itu dijual untuk penggunaan manusia, tetapi tidak termasuklah mana-mana gabungan sedemikian yang disediakan mengikut tempahan pembeli, dan untuk penggunaan serta-meratanya;',
          '(b) bagi tembakau, mana-mana proses yang menukarkan mana-mana tembakau mentah atau daun kepada tembakau yang sesuai untuk dihisap, dihidu atau dikunyah, dan termasuklah pembuatan rokok daripada tembakau yang telah dihasilkan;',
          '(c) berkenaan dengan petroleum, proses penapisan yang termasuk pengasingan, penukaran, penulenihan dan pencampuran aliran penapisan atau aliran petrokimia; dan',
          '(d) bagi kes-kes yang lain, penukaran melalui cara manual atau mekanikal bahan organik atau tak organik kepada suatu produk baharu dengan mengubah saiz, bentuk, komposisi, sifat atau kualiti bahan sedemikian dan termasuklah pemasangan bahagian-bahagian menjadi sekejap jentera atau produk lain, tetapi tidak termasuklah pemasangan jentera atau kelengkapan bagi tujuan pembinaan;',
        ],
      },
      {
        kind: 'quote',
        term: 'nakhoda',
        text: 'bermaksud mana-mana orang (kecuali juruterbang atau tuan pelabuhan) yang untuk masa mempunyai kawalan atau jagaan terhadap suatu kapal;',
        items: [],
      },
      {
        kind: 'quote',
        term: 'Menteri',
        text: 'bermaksud Menteri yang bertanggungjawab bagi kewangan;',
        items: [],
      },
      {
        kind: 'quote',
        term: 'sijil asal bukan keutamaan',
        text: 'bermaksud suatu dokumen khas yang mengenal pasti barang, yang mana pihak berkuasa penerbit yang berkuasa untuk menerbitkan dokumen sedemikian mengesahkan secara tegas bahawa barang yang berkaitan dengan sijil itu berasal dari Malaysia;',
        items: [],
      },
      {
        kind: 'quote',
        term: 'pegawai kastam',
        text: 'bermaksud--',
        items: [
          '(a) Ketua Pengarah;',
          '(b) mana-mana Timbalan Ketua Pengarah Kastam dan Eksais yang dilantik di bawah subseksyen 3(1);',
          '(c) mana-mana Penolong Ketua Pengarah, Pengarah, Timbalan Pengarah, Penolong Pengarah Kanan dan Penolong Pengarah Kastam dan Eksais yang dilantik di bawah subseksyen 3(1);',
          '(d) mana-mana Penguasa Kanan, Penguasa, Penolong Penguasa Ketua, Penolong Penguasa Kanan atau Penolong Penguasa Kastam dan Eksais yang dilantik di bawah subseksyen 3(4); dan',
          '(e) mana-mana Pegawai Kastam Ketua, Pegawai Kastam Kanan atau Pegawai Kastam yang dilantik di bawah seksyen 4;',
        ],
      },
      {
        kind: 'quote',
        term: 'asal barang',
        text: '--',
        items: [
          '(a) berkenaan dengan layanan tarif keutamaan, bermaksud negara di mana barang itu diperoleh, dihasilkan atau dianggap telah dihasilkan sepenuhnya mengikut peraturan asal yang berkenaan yang diterima pakai dalam rangka kerja perjanjian antarabangsa atau serantau yang berkuat kuasa; dan',
          '(b) berkenaan dengan layanan tarif bukan keutamaan, bermaksud Malaysia, di mana barang itu diperoleh, dihasilkan atau dianggap telah dihasilkan sepenuhnya mengikut peraturan yang diterima pakai di Malaysia;',
        ],
      },
      {
        kind: 'quote',
        term: 'pemilik',
        text: '--',
        items: [
          '(a) berkenaan dengan barang, termasuklah mana-mana orang (selain pegawai kastam yang bertindak dalam kapasiti rasminya) yang menjadi atau mengaku sebagai pemilik, pengimport, pengeksport, konsainee, ejen atau orang yang memiliki, atau berkepentingan sebenar dalam, atau mempunyai apa-apa kawalan terhadap, atau kuasa pelupusan ke atas, barang itu; dan',
          '(b) berkenaan dengan mana-mana kapal terbang, kapal atau kenderaan, termasuklah penyewa, penyewa pajak dan mana-mana orang yang bertindak sebagai ejen bagi pemilik atau yang menerima freet atau caj lain yang perlu dibayar berkenaan dengan kapal terbang, kapal atau kenderaan itu;',
        ],
      },
      {
        kind: 'quote',
        term: 'pemilik',
        text: 'berkenaan dengan kapal termasuklah setiap orang yang bertindak sebagai ejen bagi pemilik atau yang menerima freet atau caj lain yang perlu dibayar berkenaan dengan kapal itu;',
        items: [],
      },
      {
        kind: 'quote',
        term: 'Semenanjung Malaysia',
        text: 'mempunyai makna yang diberikan kepadanya dalam seksyen 3 Akta Tafsiran 1948 dan 1967 [Akta 388], dan termasuklah Wilayah Persekutuan.',
        items: [],
      },
      {
        kind: 'quote',
        term: 'petroleum',
        text: 'bermaksud mana-mana minyak mineral atau hidrokarbon berkaitan dalam bentuk pepejal, cecair atau gas yang wujud dalam keadaan aslinya dan termasuklah petrolisin kepala selongsong, syal bitumen, mendapan berlapis yang lain daripada mana-mana minyak boleh diekstrak secara komersial dan produk petroleum yang diperoleh daripada proses pengilangan;',
        items: [],
      },
      {
        kind: 'quote',
        term: 'juruterbang kapal terbang',
        text: 'bermaksud setiap orang yang mempunyai atau mengambil pemerintahan atau jagaan terhadap suatu kapal terbang;',
        items: [],
      },
      {
        kind: 'quote',
        term: 'artikel pos',
        text: 'bermaksud suatu surat, kad pos, akhbar, buku, dokumen, risalah, bungkusan corak atau contoh, bungkusan, pakej atau mana-mana benda atau barang lain yang boleh dihantar, dipungut atau dihantar pulang melalui pos;',
        items: [],
      },
      {
        kind: 'quote',
        term: 'sijil asal keutamaan',
        text: 'bermaksud suatu dokumen khas yang mengenal pasti barang, yang mana pihak berkuasa penerbit yang berkuasa untuk menerbitkan dokumen sedemikian mengesahkan secara tegas bahawa barang yang berkaitan dengan sijil itu berasal dari suatu negara tertentu mengikut peraturan asal yang diterima pakai dalam rangka kerja perjanjian antarabangsa atau serantau yang berkuat kuasa;',
        items: [],
      },
      {
        kind: 'quote',
        term: 'layanan tarif keutamaan',
        text: "bermaksud kadar-kadar duti import yang diterbitkan dalam perintah yang dibuat di bawah seksyen 11 yang terpakai bagi barang yang berasal daripada negara pengeksport mengikut perjanjian perdagangan yang berkenaan;'",
        items: [],
      },
      {
        kind: 'quote',
        term: 'kapal pencegah',
        text: 'bermaksud mana-mana kapal yang digunakan bagi pencegahan penyeludupan atau bagi mana-mana tujuan lain berkenaan dengan kastam;',
        items: [],
      },
      {
        kind: 'quote',
        term: 'pengeluar',
        text: 'bermaksud orang yang menjalankan pengeluaran barang yang termasuk penanaman, pengusahaan, pemeliharaan, perlombongan, penuaian, perikanan, perangkapan, pemburuan, penangkapan, pengumpulan, pembiakan, pengekstrakan, akuakultur, pengutipan, pengilangan, pemprosesan atau pemasangan barang itu;',
        items: [],
      },
      {
        kind: 'quote',
        term: 'barang terlarang',
        text: 'bermaksud barang yang import atau eksportnya dilarang, sama ada secara mutlak atau bersyarat, oleh suatu perintah di bawah seksyen 31 dan mana-mana perundangan subsidiari yang dibuat di bawah Akta ini atau oleh mana-mana undang-undang bertulis yang lain;',
        items: [],
      },
      {
        kind: 'quote',
        term: 'pegawai kastam yang berkenaan',
        text: 'bermaksud mana-mana pegawai kastam yang bertindak dalam penyempurnaan tugasnya di bawah Akta ini, sama ada tugas sedemikian diberikan kepadanya secara khas atau umum, atau secara tersurat atau dengan tak tersurat;',
        items: [],
      },
      {
        kind: 'quote',
        term: 'putusan awam',
        text: 'bermaksud putusan awam yang dibuat oleh Ketua Pengarah di bawah seksyen 10F;',
        items: [],
      },
      {
        kind: 'quote',
        term: 'pelepasan',
        text: 'berkenaan dengan barang, bermaksud tindakan oleh pegawai kastam yang berkenaan untuk membenarkan barang yang telah menyiapkan penyiapan kastam diletakkan di bawah pelupusan pemilik barang sedemikian;',
        items: [],
      },
      {
        kind: 'quote',
        term: 'jalan',
        text: 'termasuklah mana-mana laluan darat yang ditetapkan;',
        items: [],
      },
      {
        kind: 'quote',
        term: 'laut',
        text: 'termasuklah perairan pedalaman;',
        items: [],
      },
      {
        kind: 'quote',
        term: 'pegawai kastam kanan',
        text: 'bermaksud--',
        items: [
          '(a) Ketua Pengarah;',
          '(b) mana-mana Timbalan Ketua Pengarah Kastam dan Eksais yang dilantik di bawah subseksyen 3(1);',
          '(c) mana-mana Penolong Ketua Pengarah, Pengarah, Timbalan Pengarah, Penolong Pengarah Kanan dan Penolong Pengarah Kastam dan Eksais yang dilantik di bawah subseksyen 3(1);',
          '(d) mana-mana Penguasa Kanan, Penguasa, Penolong Penguasa Ketua, Penolong Penguasa Kanan atau Penolong Penguasa Kastam dan Eksais yang dilantik di bawah subseksyen 3(4);',
          '(e) mana-mana pegawai kastam yang diberikan kuasa-kuasa pegawai kastam kanan di bawah subseksyen 3(5) atau seksyen 5; dan',
          '(f) mana-mana pegawai polis yang mempunyai kuasa-kuasa pegawai kastam kanan bagi maksud seksyen 8;',
        ],
      },
      {
        kind: 'quote',
        term: 'tambatan persediaan',
        text: 'bermaksud mana-mana tempat selain tempat muat atau punggah yang diluluskan di mana pegawai kastam kanan boleh, mengikut budi bicaranya, dan di bawah syarat-syarat dan dengan cara yang ditetapkannya, sama ada secara umum atau dalam apa-apa kes tertentu, membenarkan mana-mana barang dimuatkan atau dinyahmuatkan;',
        items: [],
      },
      {
        kind: 'quote',
        term: 'caj tambahan',
        text: 'bermaksud mana-mana caj yang perlu dan patut dibayar di bawah subseksyen 17B(2);',
        items: [],
      },
      {
        kind: 'quote',
        term: 'perairan wilayah',
        text: 'bermaksud perairan wilayah Malaysia;',
        items: [],
      },
      {
        kind: 'quote',
        term: 'transit',
        text: 'bermaksud pergerakan barang--',
        items: [
          '(a) antara dua atau lebih pejabat kastam di Malaysia; atau',
          '(b) dari suatu pejabat kastam di mana-mana negara ke suatu pejabat kastam di Malaysia (termasuklah barang yang dipindah muat) bagi tujuan tunggal untuk dibawa keluar ke negara lain;',
        ],
      },
      {
        kind: 'quote',
        term: 'pindah muatan',
        text: 'bermaksud--',
        items: [
          '(a) pemindahan barang daripada suatu kapal atau kapal terbang kepada kapal atau kapal terbang yang lain; atau',
          '(b) punggahan barang daripada suatu kapal atau kapal terbang dan penyimpanan barang sedemikian dalam suatu gudang kastam atau gudang berlesen atau dalam suatu gudang atau tempat lain yang diluluskan oleh Ketua Pengarah,',
        ],
      },
      {
        kind: 'paragraph',
        text: 'bagi tujuan pengapalan keluar dari Malaysia atas kapal atau kapal terbang lain itu dalam kawasan bidang kuasa pejabat kastam yang sama berkenaan dengan pengimportan dan pengeksportan;',
      },
      {
        kind: 'quote',
        term: 'barang tidak lulus kastam',
        text: 'bermaksud barang berkenaan dengan mana-mana pelanggaran peruntukan Akta ini atau mana-mana perundangan subsidiari yang dibuat di bawahnya telah dilakukan;',
        items: [],
      },
      {
        kind: 'quote',
        term: 'nilai',
        text: '--',
        items: [
          '(a) berkenaan dengan barang yang diimport, bermaksud nilai kastam yang ditentukan di bawah peraturan-peraturan yang dibuat di bawah subseksyen 142(35B); dan',
          '(b) berkenaan dengan barang yang akan dieksportkan, bermaksud harga yang akan diterima oleh pengeksport bagi barang itu, dikira sehingga peringkat di mana barang itu dilepaskan oleh Kastam di tempat eksport;',
        ],
      },
      {
        kind: 'paragraph',
        text: '(1A) Bagi maksud Akta ini, suatu zon bebas hendaklah dianggap sebagai suatu tempat di luar kawasan kastam utama, dan peruntukan seksyen 31 dan Bahagian IVA, V, VI dan VII Akta ini terpakai bagi suatu zon bebas.";',
      },
      {
        kind: 'paragraph',
        text: 'Dalam subseksyen ini, ungkapan "zon bebas" mempunyai makna yang diberikan kepadanya di bawah seksyen 26 Akta Zon Bebas 1990 [Akta 438].',
      },
      {
        kind: 'paragraph',
        text: '(1B) Bagi maksud subseksyen (1A)--',
      },
      {
        kind: 'item',
        text: '(a) "zon bebas" bermaksud mana-mana kawasan di Malaysia yang telah diisytiharkan oleh Menteri sebagai zon perdagangan bebas atau zon industri bebas di bawah Akta Zon Bebas 1990 [Akta 438]; dan',
      },
      {
        kind: 'item',
        text: '(b) "kawasan kastam utama" bermaksud mana-mana bahagian Malaysia tidak termasuk suatu zon bebas, Labuan, Langkawi, Tioman dan Pangkor.',
      },
      {
        kind: 'item',
        text: '(2) Bagi tujuan Akta ini, barang hendaklah dianggap berada di bawah kawalan kastam selagi barang itu disimpan atau dipegang dalam mana-mana gudang kastam atau gudang berlesen, gudang atau tempat lain yang diluluskan oleh Ketua Pengarah, pangkalan bekal petroleum, pejabat pos, atau dalam mana-mana pengangkutan daripada mana-mana barang itu tidak boleh dikeluarkan kecuali dengan kebenaran pegawai kastam yang berkenaan.',
      },
    ],
  },
]
